// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplatev2 = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/others": {
            "get": {
                "tags": [
                    "其他内容"
                ],
                "summary": "获取",
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"success\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "其他内容"
                ],
                "summary": "修改",
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"success\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "其他内容"
                ],
                "summary": "添加",
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"success\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "其他内容"
                ],
                "summary": "删除",
                "responses": {
                    "200": {
                        "description": "{\"code\":\"200\",\"msg\":\"success\",\"data\":\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfov2 holds exported Swagger Info so clients can modify it
var SwaggerInfov2 = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/v2",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server.",
	InfoInstanceName: "v2",
	SwaggerTemplate:  docTemplatev2,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfov2.InstanceName(), SwaggerInfov2)
}
